version: "3.9"

services:
  webvim:
    build: .
    ports:
      - "80:3000"
    environment:
      - USER=dev
      - PASSWORD=dev
      - WORKSPACE_NAME=workspace
    volumes:
      - .:/home/dev/workspace
      # remove to pull .config from github
      - ~/.config:/home/dev/.config
      - ~/.ssh:/home/dev/.ssh:ro
      - ~/.gitconfig:/home/dev/.gitconfig:ro
    restart: unless-stopped
