version: "3.9"

services:
  webvim:
    build: .
    image: delapf/webvim
    container_name: webvim
    privileged: true
    ports:
      # Wetty Port
      - "3000:3000"
      # React Port
      - "8080:8080"
      # Firebase Port
      - "9005:9005"
    environment:
      - USER=dev
      - PASSWORD=dev
    volumes:
      # Setup Script
      - ./setup.sh:/usr/local/bin/setup.sh
      - ./packer_sync.sh:/usr/local/bin/packer_sync.sh
      # change '.' to wanted dir on host
      #- .:/home/dev/workspace
      - /mnt/d/dev:/home/dev/dev
      # remove to pull .config from github
      - ~/.config:/home/dev/.config
      - ~/.ssh:/home/dev/.ssh:ro
      - ~/.gitconfig:/home/dev/.gitconfig:ro
    restart: unless-stopped
