version: "3.9"

services:
  webvim:
    build: .
    image: delapf/webvim
    container_name: webvim
    ports:
      - "80:3000"
    environment:
      - USER=dev
      - PASSWORD=dev
    volumes:
      # change '.' to wanted dir on host
      - .:/home/dev/workspace
      # remove to pull .config from github
      - ~/.config:/home/dev/.config
      - ~/.ssh:/home/dev/.ssh:ro
      - ~/.gitconfig:/home/dev/.gitconfig:ro
    restart: unless-stopped
